In [54]:
import numpy as np

In [50]:
# 1
num1= np.arange(1, 16)

num1.resize(4, 4) 
display(num1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [51]:
#2
num2= np.arange(10, 51, 5)

num2.resize(4, 2) 
display(num2)

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [55]:
#3
num3= np.random.randint(1, 101, (3, 3))

print('max', num3.max())  # max
print('min', num3.min()) 
display(num3)

max 89
min 14


array([[18, 89, 48],
       [26, 46, 14],
       [83, 52, 49]], dtype=int32)